"""Application-wide configuration constants for HF-based ASR."""

# Model
MODEL_NAME = "badrex/w2v-bert-2.0-kinyarwanda-asr-1000h"
TARGET_SAMPLE_RATE = 16_000

# Audio chunking (sliding-window)
CHUNK_DURATION_MS = 22_000
OVERLAP_DURATION_MS = 3_000
MILLISECONDS_PER_SECOND = 1000
CHUNK_DURATION_SECS = CHUNK_DURATION_MS / MILLISECONDS_PER_SECOND
OVERLAP_DURATION_SECS = OVERLAP_DURATION_MS / MILLISECONDS_PER_SECOND
AUDIO_PEAK_NORMALISATION_TARGET = 0.95

# Scheduler / admission
MAX_PRIMARY_SLOTS = 2
MAX_SHORT_SLOTS = 1
SHORT_JOB_THRESHOLD_SECS = 30.0
MAX_AUDIO_DURATION_SECS = 180.0

# Durable state (HF dataset)
HF_DATASET_REPO = "mbaza-nlp/stt-job-state"
JOB_STATE_FILE = "jobs.json"
JOB_STATE_DIR = "jobs"  # Hub dataset subdirectory for sharded state files
CACHE_POLL_INTERVAL_SECS = 5

# Hub backoff settings
BACKOFF_BASE_SECS = 10
BACKOFF_MAX_SECS = 120
BACKOFF_MULTIPLIER = 2
