"""Application configuration constants."""

CACHE_POLL_INTERVAL_SECS = 5
TARGET_SAMPLE_RATE = 16_000
MAX_AUDIO_DURATION_SECS = 180.0
SHORT_JOB_THRESHOLD_SECS = 30.0
MAX_PRIMARY_SLOTS = 2
MAX_SHORT_SLOTS = 1
CHUNK_DURATION_SECS = 22
JOB_STATE_FILE = "jobs.json"
